<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>c</string>
		<string>h</string>
	</array>
	<key>name</key>
	<string>Enforce</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\#include</string>
			<key>name</key>
			<string>keyword.control.import.enforce</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#ifdef|\#ifndef|\#else|\#endif</string>
			<key>name</key>
			<string>keyword.control.other.enforce</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#define|\#undef</string>
			<key>name</key>
			<string>keyword.control.declaration.enforce</string>
		</dict>
		<dict>
			<key>match</key>
			<string>__LINE__|__FILE__</string>
			<key>name</key>
			<string>keyword.control.preproc.enforce</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#include</string>
			<key>name</key>
			<string>keyword.control.import.enforce</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&gt;\=|&lt;\=|\=\=|\!\=|&gt;|&lt;</string>
			<key>name</key>
			<string>keyword.operator.comparison.enforce</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>keyword.operator.assignment.enforce</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|\*|\/|%|~|&amp;|^</string>
			<key>name</key>
			<string>keyword.operator.arithmatic.enforce</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.enforce</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.enforce</string>
		</dict>
		<dict>
			<key>match</key>
			<string>/\*\*/</string>
			<key>name</key>
			<string>comment.block.empty.enforce</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.enforce</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.c</string>
	<key>uuid</key>
	<string>387D556D-61C0-460F-B7FA-6088840CCEDA</string>
</dict>
</plist>
